# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
  name: Build
  runs-on: ubuntu-latest
  strategy:
    matrix:
      pnpm-version: [8]
      node-version: [18]
  permissions:
    contents: 'read'
    actions: 'read'

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup pnpm ${{ matrix.pnpm-version }}
      uses: pnpm/action-setup@v2
      with:
        version: ${{ matrix.pnpm-version }}

    - name: Setup nrwl
      uses: nrwl/nx-set-shas@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
        run: pnpm install

    - name: Build affected
        run: npx nx affected -t build 